oldLighting=false
underwaterOverlay=false
sun=true
moon=true
stars=false
vignette=false
dynamicHandLight=true
clouds = off

# Screen Setup
screen.columns=1
screen=<empty> [EFFECTS_SCREEN] [WAVING_SCREEN] [SHADOW_SCREEN] [WATER_SCREEN] [RAYTRACING_SCREEN]

# Ray Tracing Screen
screen.RAYTRACING_SCREEN.columns=1
screen.RAYTRACING_SCREEN=<empty> RAY_TRACING RAY_TRACING_QUALITY GI_STRENGTH GI_RADIUS <empty> COLORED_LIGHTING COLORED_LIGHT_STRENGTH <empty> PBR NORMAL_MAP_STRENGTH SPECULAR_STRENGTH EMISSIVE_STRENGTH

# Effects Screen
screen.EFFECTS_SCREEN.columns=1
screen.EFFECTS_SCREEN=<empty> VIGNETTE GODRAYS LENS_EFFECTS BLOOM SQUARE_SUN_MOON TAA SHARPENING <empty> LOW_LIGHT_LEVEL LOW_LIGHT_BOOST

# Waving Screen
screen.WAVING_SCREEN.columns=1
screen.WAVING_SCREEN=<empty> WAVING_PLANTS WAVING_LEAVES WAVING_GRASS WAVING_WHEAT WAVING_FLOWERS WAVING_FIRE WAVING_LAVA WAVING_LILYPAD

# Shadows Screen
screen.SHADOW_SCREEN.columns=1
screen.SHADOW_SCREEN=<empty> SHADOW_QUALITY <empty> shadowDistance

# Water Screen
screen.WATER_SCREEN.columns=1
screen.WATER_SCREEN=<empty> WATER_WAVES WATER_CAUSTICS WATER_REFLECTIONS

# Sliders
sliders=shadowDistance